# Generated by Django 4.0 on 2026-02-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_id', models.BigIntegerField(unique=True)),
                ('corporation_name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corporation',
                'verbose_name_plural': 'Corporations',
                'ordering': ['corporation_name'],
                'permissions': (('view_corp_hangar', 'Can view corporation hangar'),),
            },
        ),
        migrations.CreateModel(
            name='HangarDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_id', models.IntegerField()),
                ('division_name', models.CharField(max_length=100)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='corp_inventory.corporation')),
            ],
            options={
                'verbose_name': 'Hangar Division',
                'verbose_name_plural': 'Hangar Divisions',
                'ordering': ['corporation', 'division_id'],
                'unique_together': {('corporation', 'division_id')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.BigIntegerField(unique=True)),
                ('location_name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('station', 'Station'), ('structure', 'Structure')], max_length=20)),
                ('system_id', models.BigIntegerField(blank=True, null=True)),
                ('system_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region_id', models.BigIntegerField(blank=True, null=True)),
                ('region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='HangarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.BigIntegerField(unique=True)),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=255)),
                ('quantity', models.BigIntegerField()),
                ('location_flag', models.CharField(max_length=50)),
                ('is_singleton', models.BooleanField(default=False)),
                ('is_blueprint_copy', models.BooleanField(default=False)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangar_items', to='corp_inventory.corporation')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='corp_inventory.hangardivision')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='corp_inventory.location')),
            ],
            options={
                'verbose_name': 'Hangar Item',
                'verbose_name_plural': 'Hangar Items',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='HangarTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('added', 'Item Added'), ('removed', 'Item Removed'), ('quantity_changed', 'Quantity Changed'), ('location_changed', 'Location Changed')], max_length=20)),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=255)),
                ('quantity_change', models.BigIntegerField()),
                ('old_quantity', models.BigIntegerField(blank=True, null=True)),
                ('new_quantity', models.BigIntegerField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='corp_inventory.corporation')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='corp_inventory.hangardivision')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='corp_inventory.location')),
            ],
            options={
                'verbose_name': 'Hangar Transaction',
                'verbose_name_plural': 'Hangar Transactions',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='HangarSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('total_items', models.IntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unique_types', models.IntegerField()),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='corp_inventory.corporation')),
            ],
            options={
                'verbose_name': 'Hangar Snapshot',
                'verbose_name_plural': 'Hangar Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('item_added', 'Item Added'), ('item_removed', 'Item Removed'), ('quantity_threshold', 'Quantity Threshold'), ('value_threshold', 'Value Threshold')], max_length=20)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('threshold_value', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='corp_inventory.corporation')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to='corp_inventory.hangardivision')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['corporation', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='hangartransaction',
            index=models.Index(fields=['-detected_at'], name='corp_invent_detecte_idx'),
        ),
        migrations.AddIndex(
            model_name='hangartransaction',
            index=models.Index(fields=['corporation', 'type_id'], name='corp_invent_corp_type_idx'),
        ),
        migrations.AddIndex(
            model_name='hangaritem',
            index=models.Index(fields=['corporation', 'location'], name='corp_invent_corp_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='hangaritem',
            index=models.Index(fields=['type_id'], name='corp_invent_type_id_idx'),
        ),
    ]
